Clarify review input validation
Assisted-by: Gemini <gemini@google.com>

Co-authored-by: kachick <1180335+kachick@users.noreply.github.com>

diff --git a/.github/workflows/nixpkgs-review.yml b/.github/workflows/nixpkgs-review.yml
--- a/.github/workflows/nixpkgs-review.yml
+++ b/.github/workflows/nixpkgs-review.yml
@@ -67,8 +67,14 @@ jobs:
           # https://github.com/Mic92/nixpkgs-review/blob/055465e55d131ffb1e1617f46d3bade0b87bbe69/nixpkgs_review/builddir.py#L24-L36
           echo "cache_dir=${XDG_CACHE_HOME:-${HOME}/.cache}" | tee -a "$GITHUB_OUTPUT"
 
+      - name: Validate options
+        if: ${{ inputs.args != '' && inputs.pr-number != '' }}
+        run: |
+          echo '❌ Error: Specify either "PR number" or "Customized arguments", not both.'
+          exit 2
+
       - name: Validate PR number
-        if: ${{ inputs.pr-number != '' && inputs.args == '' }}
+        if: ${{ inputs.pr-number != '' }}
         run: |
           input="${{ github.event.inputs.pr-number }}"
 
@@ -141,7 +147,7 @@ jobs:
           nix profile add "${url}#nixpkgs-review" "${url}#nix-eval-jobs"
 
       - name: Run binary-cached nixpkgs-review for PR
-        if: ${{ inputs.pr-number != '' && inputs.args == '' }}
+        if: ${{ inputs.pr-number != '' }}
         env:
           # https://github.com/Mic92/nixpkgs-review/blob/055465e55d131ffb1e1617f46d3bade0b87bbe69/README.md?plain=1#L239-L260
           GITHUB_TOKEN: '${{ github.token }}'
